### ISSUE TITLE
error: can't find crate for `rustc_serialize` when used via Cargo

### ISSUE THREAD

**Issue by AngryLawyer** [sebcrozet/nphysics#25]
So, when I have the following in my Cargo.toml:

```[dependencies.nphysics2df64]
git = "https://github.com/sebcrozet/nphysics"
```

I seem to get the following:

```Compiling nphysics2df64 v0.1.0 (https://github.com/sebcrozet/nphysics#267f1307)
/Users/tony/.cargo/git/checkouts/nphysics-d13c65e323a1814d/master/src/lib.rs:90:1: 90:51 error: can't find crate for `rustc_serialize`
/Users/tony/.cargo/git/checkouts/nphysics-d13c65e323a1814d/master/src/lib.rs:90 extern crate "rustc-serialize" as rustc_serialize;```

Looking at the dependencies in nphysics, you're pulling in rustc-serialize, but it just doesn't seem to be able to see it.

I've tried including rustc-serialize in my main project, and I've tried all the iterations of nphysics possible, and it stays not working.

Any ideas?

**Comment by sbward** [comment]
+1

**Comment by sebcrozet** [comment]
Unfortunately, I fail to reproduce the bug. I tried with the following `Cargo.toml`:

```toml
[package]
name    = "test"
version = "1.0.0"
authors = []

[dependencies.nphysics]
features = [ "2df32" ]
git = "git://github.com/sebcrozet/nphysics"

[[bin]]
name = "test"
path = "./main.rs"
```
 and the following main file:

```rust
extern crate nphysics;

fn main() {
}
```

Did I miss something to reproduce the error? Also, did you run a `cargo update` lately?
